export const BD_DIVISIONS = [
  'Dhaka',
  'Chattogram',
  'Rajshahi',
  'Khulna',
  'Barishal',
  'Sylhet',
  'Rangpur',
  'Mymensingh',
];

// Highlighted districts with Dhaka and Bogura
export const POPULAR_DISTRICTS = [
  'Dhaka',
  'Bogura',
  'Gazipur',
  'Narayanganj',
  'Chattogram',
  'Sylhet',
  'Rajshahi',
  'Khulna',
  'Cumilla',
];

export const ALL_DISTRICTS: Record<string, string[]> = {
  Dhaka: [
    'Dhaka',
    'Gazipur',
    'Narayanganj',
    'Tangail',
    'Narsingdi',
    'Faridpur',
    'Manikganj',
    'Munshiganj',
    'Gopalganj',
    'Madaripur',
    'Rajbari',
    'Shariatpur',
    'Kishoreganj',
  ],
  Rajshahi: [
    'Bogura',
    'Rajshahi',
    'Pabna',
    'Sirajganj',
    'Naogaon',
    'Natore',
    'Chapai Nawabganj',
    'Joypurhat',
  ],
  Chattogram: [
    'Chattogram',
    "Cox's Bazar",
    'Cumilla',
    'Feni',
    'Brahmanbaria',
    'Noakhali',
    'Chandpur',
    'Lakshmipur',
    'Rangamati',
    'Khagrachhari',
    'Bandarban',
  ],
  Khulna: [
    'Khulna',
    'Jashore',
    'Kushtia',
    'Satkhira',
    'Bagerhat',
    'Jhenaidah',
    'Chuadanga',
    'Magura',
    'Meherpur',
    'Narail',
  ],
  Sylhet: ['Sylhet', 'Moulvibazar', 'Habiganj', 'Sunamganj'],
  Barishal: ['Barishal', 'Patuakhali', 'Bhola', 'Pirojpur', 'Barguna', 'Jhalokati'],
  Rangpur: ['Rangpur', 'Dinajpur', 'Kurigram', 'Gaibandha', 'Nilphamari', 'Panchagarh', 'Thakurgaon', 'Lalmonirhat'],
  Mymensingh: ['Mymensingh', 'Jamalpur', 'Netrokona', 'Sherpur'],
};

export const DHAKA_AREAS = [
  'Banani',
  'Gulshan 1',
  'Gulshan 2',
  'Dhanmondi',
  'Uttara',
  'Mirpur',
  'Mohakhali',
  'Baridhara',
  'Bashundhara R/A',
  'Badda',
  'Mohammadpur',
  'Lalmatia',
  'Tejgaon',
  'Khilgaon',
  'Shantinagar',
  'Malibagh',
  'Motijheel',
  'Old Dhaka',
  'Puran Dhaka (Chawkbazar)',
  'Elephant Road',
  'Cantonment',
  'Nikunja',
];
